apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
        - name: hello-world
          image: hello-world
      restartPolicy: Never
